// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateSiteDesignRequestInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The display description of site design.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The alt text description of the preview image for accessibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewImageAltText { get; set; }
#nullable restore
#else
        public string PreviewImageAltText { get; set; }
#endif
        /// <summary>The URL of a preview image. If none is specified, SharePoint uses a generic image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewImageUrl { get; set; }
#nullable restore
#else
        public string PreviewImageUrl { get; set; }
#endif
        /// <summary>An array of one or more site scripts. Each is identified by an ID. The scripts will run in the order listed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SiteScriptIds { get; set; }
#nullable restore
#else
        public List<string> SiteScriptIds { get; set; }
#endif
        /// <summary>The display name of the site design.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Identifies which base template to add the design to. Use the value 64 for the Team site template, and the value 68 for the Communication site template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebTemplate { get; set; }
#nullable restore
#else
        public string WebTemplate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.CreateSiteDesignRequestInfo"/> and sets the default values.
        /// </summary>
        public CreateSiteDesignRequestInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.CreateSiteDesignRequestInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.CreateSiteDesignRequestInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.CreateSiteDesignRequestInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Description", n => { Description = n.GetStringValue(); } },
                { "PreviewImageAltText", n => { PreviewImageAltText = n.GetStringValue(); } },
                { "PreviewImageUrl", n => { PreviewImageUrl = n.GetStringValue(); } },
                { "SiteScriptIds", n => { SiteScriptIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "WebTemplate", n => { WebTemplate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("PreviewImageAltText", PreviewImageAltText);
            writer.WriteStringValue("PreviewImageUrl", PreviewImageUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("SiteScriptIds", SiteScriptIds);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("WebTemplate", WebTemplate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
