// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Group_OdataType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "#SP.Group")]
        #pragma warning disable CS1591
        SPGroup,
        #pragma warning restore CS1591
    }
}
