// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CustomResults property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Graph.Community.Models.CustomResult>? CustomResults { get; set; }
#nullable restore
#else
        public List<global::Graph.Community.Models.CustomResult> CustomResults { get; set; }
#endif
        /// <summary>The QueryId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueryId { get; set; }
#nullable restore
#else
        public string QueryId { get; set; }
#endif
        /// <summary>The QueryRuleId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueryRuleId { get; set; }
#nullable restore
#else
        public string QueryRuleId { get; set; }
#endif
        /// <summary>The RefinementResults property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.QueryResult_RefinementResults? RefinementResults { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.QueryResult_RefinementResults RefinementResults { get; set; }
#endif
        /// <summary>The RelevantResults property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.RelevantResults? RelevantResults { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.RelevantResults RelevantResults { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.QueryResult"/> and sets the default values.
        /// </summary>
        public QueryResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.QueryResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.QueryResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.QueryResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CustomResults", n => { CustomResults = n.GetCollectionOfObjectValues<global::Graph.Community.Models.CustomResult>(global::Graph.Community.Models.CustomResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "QueryId", n => { QueryId = n.GetStringValue(); } },
                { "QueryRuleId", n => { QueryRuleId = n.GetStringValue(); } },
                { "RefinementResults", n => { RefinementResults = n.GetObjectValue<global::Graph.Community.Models.QueryResult_RefinementResults>(global::Graph.Community.Models.QueryResult_RefinementResults.CreateFromDiscriminatorValue); } },
                { "RelevantResults", n => { RelevantResults = n.GetObjectValue<global::Graph.Community.Models.RelevantResults>(global::Graph.Community.Models.RelevantResults.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Graph.Community.Models.CustomResult>("CustomResults", CustomResults);
            writer.WriteStringValue("QueryId", QueryId);
            writer.WriteStringValue("QueryRuleId", QueryRuleId);
            writer.WriteObjectValue<global::Graph.Community.Models.QueryResult_RefinementResults>("RefinementResults", RefinementResults);
            writer.WriteObjectValue<global::Graph.Community.Models.RelevantResults>("RelevantResults", RelevantResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
