// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RefinementResults : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The GroupTemplateId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupTemplateId { get; set; }
#nullable restore
#else
        public string GroupTemplateId { get; set; }
#endif
        /// <summary>The ItemTemplateId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemTemplateId { get; set; }
#nullable restore
#else
        public string ItemTemplateId { get; set; }
#endif
        /// <summary>The Properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Graph.Community.Models.ResultKeyValuePair>? Properties { get; set; }
#nullable restore
#else
        public List<global::Graph.Community.Models.ResultKeyValuePair> Properties { get; set; }
#endif
        /// <summary>The Refiners property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Graph.Community.Models.Refiner>? Refiners { get; set; }
#nullable restore
#else
        public List<global::Graph.Community.Models.Refiner> Refiners { get; set; }
#endif
        /// <summary>The ResultTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultTitle { get; set; }
#nullable restore
#else
        public string ResultTitle { get; set; }
#endif
        /// <summary>The ResultTitleUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultTitleUrl { get; set; }
#nullable restore
#else
        public string ResultTitleUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.RefinementResults"/> and sets the default values.
        /// </summary>
        public RefinementResults()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.RefinementResults"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.RefinementResults CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.RefinementResults();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "GroupTemplateId", n => { GroupTemplateId = n.GetStringValue(); } },
                { "ItemTemplateId", n => { ItemTemplateId = n.GetStringValue(); } },
                { "Properties", n => { Properties = n.GetCollectionOfObjectValues<global::Graph.Community.Models.ResultKeyValuePair>(global::Graph.Community.Models.ResultKeyValuePair.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Refiners", n => { Refiners = n.GetCollectionOfObjectValues<global::Graph.Community.Models.Refiner>(global::Graph.Community.Models.Refiner.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ResultTitle", n => { ResultTitle = n.GetStringValue(); } },
                { "ResultTitleUrl", n => { ResultTitleUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("GroupTemplateId", GroupTemplateId);
            writer.WriteStringValue("ItemTemplateId", ItemTemplateId);
            writer.WriteCollectionOfObjectValues<global::Graph.Community.Models.ResultKeyValuePair>("Properties", Properties);
            writer.WriteCollectionOfObjectValues<global::Graph.Community.Models.Refiner>("Refiners", Refiners);
            writer.WriteStringValue("ResultTitle", ResultTitle);
            writer.WriteStringValue("ResultTitleUrl", ResultTitleUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
