// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchQuery : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Querytext property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Querytext { get; set; }
#nullable restore
#else
        public string Querytext { get; set; }
#endif
        /// <summary>The Refiners property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Refiners { get; set; }
#nullable restore
#else
        public string Refiners { get; set; }
#endif
        /// <summary>The RowLimit property</summary>
        public int? RowLimit { get; set; }
        /// <summary>The RowsPerPage property</summary>
        public int? RowsPerPage { get; set; }
        /// <summary>The SelectProperties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SelectProperties? SelectProperties { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SelectProperties SelectProperties { get; set; }
#endif
        /// <summary>The SortList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SortList? SortList { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SortList SortList { get; set; }
#endif
        /// <summary>The StartRow property</summary>
        public int? StartRow { get; set; }
        /// <summary>The TrimDuplicates property</summary>
        public bool? TrimDuplicates { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.SearchQuery"/> and sets the default values.
        /// </summary>
        public SearchQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.SearchQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.SearchQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.SearchQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Querytext", n => { Querytext = n.GetStringValue(); } },
                { "Refiners", n => { Refiners = n.GetStringValue(); } },
                { "RowLimit", n => { RowLimit = n.GetIntValue(); } },
                { "RowsPerPage", n => { RowsPerPage = n.GetIntValue(); } },
                { "SelectProperties", n => { SelectProperties = n.GetObjectValue<global::Graph.Community.Models.SelectProperties>(global::Graph.Community.Models.SelectProperties.CreateFromDiscriminatorValue); } },
                { "SortList", n => { SortList = n.GetObjectValue<global::Graph.Community.Models.SortList>(global::Graph.Community.Models.SortList.CreateFromDiscriminatorValue); } },
                { "StartRow", n => { StartRow = n.GetIntValue(); } },
                { "TrimDuplicates", n => { TrimDuplicates = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("Querytext", Querytext);
            writer.WriteStringValue("Refiners", Refiners);
            writer.WriteIntValue("RowLimit", RowLimit);
            writer.WriteIntValue("RowsPerPage", RowsPerPage);
            writer.WriteObjectValue<global::Graph.Community.Models.SelectProperties>("SelectProperties", SelectProperties);
            writer.WriteObjectValue<global::Graph.Community.Models.SortList>("SortList", SortList);
            writer.WriteIntValue("StartRow", StartRow);
            writer.WriteBoolValue("TrimDuplicates", TrimDuplicates);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
