// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SiteScriptActionOutcome
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failure")]
        #pragma warning disable CS1591
        Failure,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoOp")]
        #pragma warning disable CS1591
        NoOp,
        #pragma warning restore CS1591
        [EnumMember(Value = "SucceededWithException")]
        #pragma warning disable CS1591
        SucceededWithException,
        #pragma warning restore CS1591
    }
}
