// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SPListItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content type of the list item.Requires $expand=ContentType.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SPContentType? ContentType { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SPContentType ContentType { get; set; }
#endif
        /// <summary>The ContentTypeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentTypeId { get; set; }
#nullable restore
#else
        public string ContentTypeId { get; set; }
#endif
        /// <summary>Field values rendered as HTML.Requires $expand=FieldValuesAsHtml.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SPListItem_FieldValuesAsHtml? FieldValuesAsHtml { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SPListItem_FieldValuesAsHtml FieldValuesAsHtml { get; set; }
#endif
        /// <summary>Field values rendered as plain text.Requires $expand=FieldValuesAsText.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SPListItem_FieldValuesAsText? FieldValuesAsText { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SPListItem_FieldValuesAsText FieldValuesAsText { get; set; }
#endif
        /// <summary>Field values for use in edit forms.Requires $expand=FieldValuesForEdit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.SPListItem_FieldValuesForEdit? FieldValuesForEdit { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.SPListItem_FieldValuesForEdit FieldValuesForEdit { get; set; }
#endif
        /// <summary>The integer identifier of the list item.</summary>
        public int? Id { get; set; }
        /// <summary>The title of the list item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.SPListItem"/> and sets the default values.
        /// </summary>
        public SPListItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.SPListItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.SPListItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.SPListItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ContentType", n => { ContentType = n.GetObjectValue<global::Graph.Community.Models.SPContentType>(global::Graph.Community.Models.SPContentType.CreateFromDiscriminatorValue); } },
                { "ContentTypeId", n => { ContentTypeId = n.GetStringValue(); } },
                { "FieldValuesAsHtml", n => { FieldValuesAsHtml = n.GetObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesAsHtml>(global::Graph.Community.Models.SPListItem_FieldValuesAsHtml.CreateFromDiscriminatorValue); } },
                { "FieldValuesAsText", n => { FieldValuesAsText = n.GetObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesAsText>(global::Graph.Community.Models.SPListItem_FieldValuesAsText.CreateFromDiscriminatorValue); } },
                { "FieldValuesForEdit", n => { FieldValuesForEdit = n.GetObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesForEdit>(global::Graph.Community.Models.SPListItem_FieldValuesForEdit.CreateFromDiscriminatorValue); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Graph.Community.Models.SPContentType>("ContentType", ContentType);
            writer.WriteStringValue("ContentTypeId", ContentTypeId);
            writer.WriteObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesAsHtml>("FieldValuesAsHtml", FieldValuesAsHtml);
            writer.WriteObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesAsText>("FieldValuesAsText", FieldValuesAsText);
            writer.WriteObjectValue<global::Graph.Community.Models.SPListItem_FieldValuesForEdit>("FieldValuesForEdit", FieldValuesForEdit);
            writer.WriteIntValue("Id", Id);
            writer.WriteStringValue("Title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
