// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    /// <summary>
    /// Basic information about a list.(To get complete information, use the Microsoft Graph endpoint.)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SPList : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The list definition type on which the list is based.</summary>
        public int? BaseTemplate { get; set; }
        /// <summary>The Forms property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Graph.Community.Models.SPForm>? Forms { get; set; }
#nullable restore
#else
        public List<global::Graph.Community.Models.SPForm> Forms { get; set; }
#endif
        /// <summary>The GUID that identifies the list in the database.</summary>
        public Guid? Id { get; set; }
        /// <summary>The displayed title for the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.SPList"/> and sets the default values.
        /// </summary>
        public SPList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.SPList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.SPList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.SPList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "BaseTemplate", n => { BaseTemplate = n.GetIntValue(); } },
                { "Forms", n => { Forms = n.GetCollectionOfObjectValues<global::Graph.Community.Models.SPForm>(global::Graph.Community.Models.SPForm.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Id", n => { Id = n.GetGuidValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("BaseTemplate", BaseTemplate);
            writer.WriteCollectionOfObjectValues<global::Graph.Community.Models.SPForm>("Forms", Forms);
            writer.WriteGuidValue("Id", Id);
            writer.WriteStringValue("Title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
