// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Graph.Community.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SPSite : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents the unique sequential location of a change within the change log.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Graph.Community.Models.ChangeToken? CurrentChangeToken { get; set; }
#nullable restore
#else
        public global::Graph.Community.Models.ChangeToken CurrentChangeToken { get; set; }
#endif
        /// <summary>The GeoLocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeoLocation { get; set; }
#nullable restore
#else
        public string GeoLocation { get; set; }
#endif
        /// <summary>The GroupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The HubSiteId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HubSiteId { get; set; }
#nullable restore
#else
        public string HubSiteId { get; set; }
#endif
        /// <summary>The Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The IsHubSite property</summary>
        public bool? IsHubSite { get; set; }
        /// <summary>The PrimaryUri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryUri { get; set; }
#nullable restore
#else
        public string PrimaryUri { get; set; }
#endif
        /// <summary>The ServerRelativeUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerRelativeUrl { get; set; }
#nullable restore
#else
        public string ServerRelativeUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Models.SPSite"/> and sets the default values.
        /// </summary>
        public SPSite()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Graph.Community.Models.SPSite"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Graph.Community.Models.SPSite CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Graph.Community.Models.SPSite();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CurrentChangeToken", n => { CurrentChangeToken = n.GetObjectValue<global::Graph.Community.Models.ChangeToken>(global::Graph.Community.Models.ChangeToken.CreateFromDiscriminatorValue); } },
                { "GeoLocation", n => { GeoLocation = n.GetStringValue(); } },
                { "GroupId", n => { GroupId = n.GetStringValue(); } },
                { "HubSiteId", n => { HubSiteId = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "IsHubSite", n => { IsHubSite = n.GetBoolValue(); } },
                { "PrimaryUri", n => { PrimaryUri = n.GetStringValue(); } },
                { "ServerRelativeUrl", n => { ServerRelativeUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Graph.Community.Models.ChangeToken>("CurrentChangeToken", CurrentChangeToken);
            writer.WriteStringValue("GeoLocation", GeoLocation);
            writer.WriteStringValue("GroupId", GroupId);
            writer.WriteStringValue("HubSiteId", HubSiteId);
            writer.WriteStringValue("Id", Id);
            writer.WriteBoolValue("IsHubSite", IsHubSite);
            writer.WriteStringValue("PrimaryUri", PrimaryUri);
            writer.WriteStringValue("ServerRelativeUrl", ServerRelativeUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
