version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
      xunit-dependencies:
        patterns:
          - "*xunit*"
      swashbuckle-dependencies:
        patterns:
          - "*Swashbuckle*"
      microsoft-extensions-dependencies:
        patterns:
          - "*Microsoft.Extensions*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
