// <auto-generated/>
#pragma warning disable CS0618
using Graph.Community.Item._api.SiteScriptUtility.ApplySiteDesign;
using Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignMetadata;
using Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignRuns;
using Graph.Community.Item._api.SiteScriptUtility.GetSiteDesigns;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Graph.Community.Item._api.SiteScriptUtility
{
    /// <summary>
    /// Builds and executes requests for operations under \{serverRelativeSiteUrl}\_api\SiteScriptUtility
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SiteScriptUtilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ApplySiteDesign property</summary>
        public global::Graph.Community.Item._api.SiteScriptUtility.ApplySiteDesign.ApplySiteDesignRequestBuilder ApplySiteDesign
        {
            get => new global::Graph.Community.Item._api.SiteScriptUtility.ApplySiteDesign.ApplySiteDesignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSiteDesignMetadata property</summary>
        public global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignMetadata.GetSiteDesignMetadataRequestBuilder GetSiteDesignMetadata
        {
            get => new global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignMetadata.GetSiteDesignMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSiteDesignRuns property</summary>
        public global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignRuns.GetSiteDesignRunsRequestBuilder GetSiteDesignRuns
        {
            get => new global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesignRuns.GetSiteDesignRunsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSiteDesigns property</summary>
        public global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesigns.GetSiteDesignsRequestBuilder GetSiteDesigns
        {
            get => new global::Graph.Community.Item._api.SiteScriptUtility.GetSiteDesigns.GetSiteDesignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Item._api.SiteScriptUtility.SiteScriptUtilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SiteScriptUtilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{serverRelativeSiteUrl}/_api/SiteScriptUtility", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Graph.Community.Item._api.SiteScriptUtility.SiteScriptUtilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SiteScriptUtilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{serverRelativeSiteUrl}/_api/SiteScriptUtility", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
