// <auto-generated/>
using Graph.Community.Item._api.HubSites;
using Graph.Community.Item._api.Web;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Graph.Community.Item._api
{
    /// <summary>
    /// Builds and executes requests for operations under \{serverRelativeSiteUrl}\_api
    /// </summary>
    public class _apiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The HubSites property</summary>
        public Graph.Community.Item._api.HubSites.HubSitesRequestBuilder HubSites
        {
            get => new Graph.Community.Item._api.HubSites.HubSitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Web property</summary>
        public Graph.Community.Item._api.Web.WebRequestBuilder Web
        {
            get => new Graph.Community.Item._api.Web.WebRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="Graph.Community.Item._api._apiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public _apiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{serverRelativeSiteUrl}/_api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Graph.Community.Item._api._apiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public _apiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{serverRelativeSiteUrl}/_api", rawUrl)
        {
        }
    }
}
